language: node_js
node_js:
  - "4"
  - "5"
  - "6"
notifications:
  slack: platdesign:ElGXfHTPMGMnixew1MUyEeER


before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install libc-ares-dev libssl-dev uuid-dev

before_script:
    - ./travis/compile-mosquitto.sh

script:
    - ./travis/run-tests.sh
